const express = require("express")
const router = express.Router()

const authRoutes = require("./auth")
const productRoutes = require("./products")
const brandRoutes = require("./brands")
const categoryRoutes = require("./categories")
const userRoutes = require("./users")
const userPermissionsRouter = require("./userPermissions")
const activityRoutes = require("./activities")
const permissionRoutes = require("./permissions")
const importRoutes = require("./import")
const cartRoutes = require("./cart")
const budgetRoutes = require("./budgets")
const notificationRoutes = require("./notifications")
const myBudgetRoutes = require("./myBudgets")

router.use("/auth", authRoutes)
router.use("/my-budgets", myBudgetRoutes)
router.use("/cart", cartRoutes)
router.use("/budgets", budgetRoutes)
router.use("/notifications", notificationRoutes)
router.use("/products", productRoutes)
router.use("/brands", brandRoutes)
router.use("/categories", categoryRoutes)
router.use("/users", userRoutes)
router.use("/users/:userId/permissions", userPermissionsRouter)
router.use("/activities", activityRoutes)
router.use("/permissions", permissionRoutes)
router.use("/import", importRoutes)

module.exports = router
